#接口请求的期望值
request:
    except: '{"reason": "success", "result": {"men": "狗", "women": "鼠", "data": "理想的配偶，你会对他很温柔，能使他的理想世界更加接近现实。"}, "error_code": 0}'

#查询数据库
mysql:
    host: '192.168.0.219'
    port: 3306
    db: 'test'
    user: 'root'
    passwd: '123'
    charset: 'utf8'
    sql: 'select id,username from sec_custinfo'
    except: [['1', '董卓'], ['2', '张坤'], ['3', '王伟'], ['4', '王伟'], ['5', '宋军'], ['6', '陈红'], ['7', '陈红'], ['8', '王丽'], ['9', '王丽'], ['10', '宋伟']]

