logger:
    name: ITester
    level: DEBUG
    format: '%(filename)s-%(lineno)d-%(asctime)s-%(levelname)s-%(message)s'

email:
    send_email: '18877570499@163.com'
    pwd: 'NVQDMSWGOWCQKBTB'
    receiver: '1298166079@qq.com'

